### ISSUE TITLE
Unable to remove active customizations when only 1 is listed

### ISSUE THREAD

**Issue by JMG74** [aboodh95/SolutionLayerRemoval#10]
Hi ! Thank's for this really useful tool :-)

As I use it more and more, I am very annoyed by the following malfunction when I use the "Remove Active Customizations" button: 
1) It is impossible to remove the active customizations when only one item is listed.
2) When I select all the elements that have active customizations and click "Remove Active Customizations", there is always one remaining element that has not had the layer removed.

Thx in advance, best regards.

**Comment by aboodh95** [comment]
Hi @JMG74.

Thanks for these comments, I was able to reproduce all issues, and I will try to work on them in the coming week 🙌

**Comment by JMG74** [comment]
Hi aboodh95, do you have any news concerning this bug ?

**Comment by aboodh95** [comment]
Hi @JMG74, finally, the issue has been resolved 🥳🥳🥳, please install the latest update

**Comment by JMG74** [comment]
Hi aboodh95.
I confirm that I'm now able to delete the last element in the list 🥳🥳🥳
Many thanks !! and all the best.
