### ISSUE TITLE
App Version MisMatch

### ISSUE THREAD

**Issue by JamesStuder** [aboodh95/SolutionLayerRemoval#4]
Please check versioning on your plugin.  Says that 1.0.1.4 is installed and the latest is 1.2020.8.5.  I have tried multiple times and it never removes from the list of plugins that need to be upgraded.  I have seen this and experienced with my own connector.  There is a mismatch between versions in the connector, nuget and app assembly.

**Comment by aboodh95** [comment]
@JamesStuder ,
Thanks for pointing out this issue, I have released a new version that fixes it
