### ISSUE TITLE
Trying to update via Toolbox, not working

### ISSUE THREAD

**Issue by lrogers-AriaConsulting** [aboodh95/SolutionLayerRemoval#8]
Hi,

Tryin g to update this tool via XRM Toolbox, but it just stubbornly won't update. I've even downloaded the zip directly. Still shows as needing an update in the library. Am I missing something?

**Comment by aboodh95** [comment]
Hi,

I have noticed this issue 2 days back, I will try to resolve it ASAP

**Comment by MscrmTools** [comment]
@aboodh95, the issue is still there. Could you just push a new Nuget package with the same version as the assembly so that it fixes it.

**Comment by aboodh95** [comment]
@MscrmTools I have updated the version and pushed the new one, now it showing as not installed
![image](https://user-images.githubusercontent.com/12459798/155712899-47975834-8643-4743-b353-58c2fe53f3bc.png)

**Comment by MscrmTools** [comment]
@aboodh95 Your assembly is not under a Plugins folder in your Nuget package...
![image](https://user-images.githubusercontent.com/10774317/155715586-56236b0b-3d27-43b9-8603-3aeaaed9adcb.png)

**Comment by aboodh95** [comment]
@MscrmTools Can you check it now, i made it in the Plugins folder, but now it's not getting the latest version in Tool Library

**Comment by MscrmTools** [comment]
I will check on Monday
